version: "3.8"
services:
  webapp:
    container_name: event-board_gunicorn
    image: event-board:latest
    networks:
      - event-board
    restart: always
    volumes:
      - staticfiles:/app/event-board/static
    environment: 
      - DATABASE_DB=event-board
      - DATABASE_USER=usrevent
      - DATABASE_PASS=event-board
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - REDIS_HOST=redis
      - DJANGO_SECRET_KEY=CHANGEME
      - DJANGO_SETTINGS_MODULE=event-board.config.local
      - ALLOWED_HOSTS=["*"]
    depends_on:
      - db
      - redis
    
  db:
    container_name: event-board_mariadb
    image: mariadb:10.5.11
    networks:
      - event-board
    restart: always
    environment: 
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=event-board
      - MARIADB_USER=usrevent
      - MARIADB_PASSWORD=event-board
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql

  nginx:
    container_name: event-board_nginx
    image: nginx:mainline-alpine
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/app/event-board/static
    depends_on:
      - webapp
    networks:
      - event-board
    environment:
      - VIRTUAL_HOST=localhost
    ports:
      - "80:80"
      - "443:443"

  redis:
    container_name: event-board_redis
    image: redis:6
    restart: always
    networks:
      - event-board

networks:
  event-board:

volumes:
  staticfiles:
  db-data:
