# Generated by Django 3.2.5 on 2021-07-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloEvento', models.CharField(default='Evento', max_length=255, verbose_name='Evento')),
                ('fechaEvento', models.DateField(verbose_name='Fecha del evento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('apuntados', models.JSONField(null=True)),
                ('siguienteEvento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cenas.evento', verbose_name='Siguiente evento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
            ],
        ),
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.CharField(max_length=100, verbose_name='Evento')),
                ('recuento', models.IntegerField(default=0)),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cenas.evento')),
            ],
        ),
    ]
