# Generated by Django 3.2.5 on 2021-07-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='alergenos',
            field=models.JSONField(null=True),
        ),
    ]
