# Generated by Django 3.2.5 on 2021-07-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenas', '0003_evento_permitiralergenos'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleccion',
            name='usuarios',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='alergenos',
            field=models.JSONField(null=True, verbose_name='Lista de alérgenos'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='permitirAlergenos',
            field=models.BooleanField(default=False, verbose_name='Permitir alérgenos'),
        ),
    ]
