name: Build docker

on:
  release:
    types: [released]
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout de master
      uses: actions/checkout@v2
    
    - name: Login al registry
      uses: docker/login-action@v1.14.1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extrae meta para Docker
      id: meta
      uses: docker/metadata-action@v3.6.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
    - name: Build y push
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de master
      uses: actions/checkout@v2
      
    - name: Login a Dockerhub
      uses: docker/login-action@v1.14.1
      with:
        username: thepotatocamera
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Extrae meta para Docker
      id: meta
      uses: docker/metadata-action@v3.6.1
      with:
        images: ${{ env.IMAGE_NAME }}
        
    - name: Build y push
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
